name: 'test'

inputs:
  list:
    description: 'test list'
    required: true

runs:
  using: "composite"
  steps:
    - name: chmod
      run: sudo chmod +x ${{ github.action_path }}/test.sh
      shell: bash
    - name: echo list
      run: ${{ github.action_path }}/test.sh
      shell: bash
      env:
        INPUT_LIST: ${{ inputs.list }}
