name: 'test'

inputs:
  list:
    description: 'test list'
    required: true

runs:
  using: "composite"
  steps:
    - name: echo list
      run: | 
        sudo chmod +x ${{ github.action_path }}/test.sh
        sudo bash ${{ github.action_path }}/test.sh
      env:
        INPUT_LIST: ${{ inputs.list }}
